### ISSUE TITLE
Use webassembly for better performane

### ISSUE THREAD

**Issue by j209** [xeokit/sdk#45]
what about using wasm([Assemblyscript](https://www.assemblyscript.org/) in this project for better performace?

**Comment by xeolabs** [comment]
No reason why not! 

We have the resources to implement WASM modules, but for development simplicity we're keeping things TypeScript at least in the early stages. 

I'm thinking it's best to profile the JS performance and insert it into specific areas that have bottlenecks (math lib, calculation of triangle mesh edge indices, etc).

We'd welcome any suggestions on where to use it in this API. 

Also if you can contribute any WASM implementations of this project's functionality, we'd definitely consider PRs.
