### ISSUE TITLE
Can not install @xeokit/scene... via npm package

### ISSUE THREAD

**Issue by RyugaRyuzaki** [xeokit/sdk#5]
Hi teams, i can not install this via npm. Is this opensource? Thank all teams

**Comment by xeolabs** [comment]
Oops, looks like the minified build may not have deployed for last 2.4.0-alpha-99. Try the unminified library for now, or an earlier version, until we redeploy 2.4.0-alpha-100 (tomorrow) - this should be OK in the meantime: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.4.0-alpha-97

**Comment by xeolabs** [comment]
Should be OK now: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.4.0-alpha-100

Let us know if you still get problems.

**Comment by RyugaRyuzaki** [comment]
> Should be OK now: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.4.0-alpha-100
> 
> Let us know if you still get problems.

Awsome! Everything is ok! However how can i use this with a complex geometry that i used Revit add-in to export :```sceneModel.createGeometry({ // Define a box-shaped geometry
    id: "boxGeometry",
    primitive: TrianglesPrimitive,
    positions: [-1, -1, -1, 1, -1, -1, ],//complex
    uvs: [1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, ],//complex
    indices: [0, 1, 2, 0, 2, 3, 4, 5, 6, 4, ]//complex
});```

**Comment by RyugaRyuzaki** [comment]
> Should be OK now: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.4.0-alpha-100
> 
> Let us know if you still get problems.

Something went wrong and load an ifc model ~60MB to slow 
![image](https://github.com/xeokit/sdk/assets/89787521/5b9318ce-b83c-4324-81ac-2e30f3f3d22e)

**Comment by RyugaRyuzaki** [comment]
> Should be OK now: https://www.npmjs.com/package/@xeokit/xeokit-sdk/v/2.4.0-alpha-100
> 
> Let us know if you still get problems.

10 minutes still unloaded!
![image](https://github.com/xeokit/sdk/assets/89787521/7f24dcd7-de77-4915-b8c7-92d659970dcc)

**Comment by paireks** [comment]
Hey @RyugaRyuzaki :)

This repository is for Xeokit v3, which is not ready as it is still alpha, and currently you won't see anything in the viewer yet. If you'd like to experiment with Xeokit itself, you can check v2, which is here and ready: https://github.com/xeokit/xeokit-sdk

There are lot of examples here for v2: https://xeokit.github.io/xeokit-sdk/examples/index.html

I will let you know once v3 will be ready for some tests ;)

**Comment by xeolabs** [comment]
OK yes, this issue report got me confused. 

It seems to be a two things: npm module not found, and IFC model loading slowly with WebIFCLoaderPlugin, which belongs to @xeokit/xeokit-sdk, a different repository.

As @paireks mentioned, this repository (xeokit V3) is still be developed and no NPM packages have been published yet. We will publish packages once the WebGL renderer here is finished.

The WebIFCLoaderPlugin of @xeokit/xeokit-sdk (V2) is functioning correctly in the latest xeokit-sdk release, so I don;t think we have anything to do here.

**Comment by RyugaRyuzaki** [comment]
@paireks @xeolabs I was stack this for 6 months ago, so i dropped this.  yes, i need this library for testing export from Revit, and idea for this?

**Comment by paireks** [comment]
@RyugaRyuzaki if you're looking for open-source solutions you can check this: https://xeokit.notion.site/Converting-IFC-Models-to-XKT-using-3rd-Party-Open-Source-Tools-c373e48bc4094ff5b6e5c5700ff580ee

Also for your information v3 supports .bim, so in the future workflow using your https://github.com/RyugaRyuzaki/DotBimConvert/tree/main/RevitExporter project should be possible. But for current version (v2) I'd check link above.
